### ISSUE TITLE
fix(smart_crusher): lossless_only removed from Rust SmartCrusherConfig but Python shim still passes it — compression silently fails

### ISSUE THREAD

**Issue by sfc-gh-nashukla** [headroomlabs-ai/headroom#1478]
## Bug

After merging Stage 3g (Rust SmartCrusher rewrite), compression silently fails with:

```
Compression with smart_crusher failed: SmartCrusherConfig.__new__() got an unexpected keyword argument 'lossless_only'
```

Tokens saved drops to 0 across all compression paths.

## Root Cause

`_build_rust()` in `headroom/transforms/smart_crusher.py` (line ~413) still passes `lossless_only` to the Rust `SmartCrusherConfig`:

```python
kwargs["lossless_only"] = lossless_only
rust_cfg = self._RustSmartCrusherConfig(**kwargs)
```

But the Rust struct no longer accepts this field — it was removed in Stage 3g.

## Reproduce

```python
import sys
sys.path.insert(0, '.')
from headroom import compress
import json

msgs = [{"role": "tool", "content": json.dumps([{"TABLE_NAME": f"T_{i}", "ROW_COUNT": i*1000} for i in range(50)], indent=2)}]
r = compress(msgs)
print("saved:", r.tokens_saved)  # prints 0, should be ~600+
```

## Fix

In `_build_rust()`, remove `lossless_only` from the kwargs before passing to Rust:

```python
kwargs = dict(self._rust_cfg_kwargs)
kwargs.pop("lossless_only", None)  # removed from Rust SmartCrusherConfig in Stage 3g
rust_cfg = self._RustSmartCrusherConfig(**kwargs)
```

Also remove `"lossless_only": self._lossless_only` from `_rust_cfg_kwargs` dict.

## Impact

All compression paths broken — MCP `headroom_compress`, proxy SmartCrusher, library `compress()` all return 0 savings.

Discovered while running e2e tests for the Cortex Code provider (PR #1474).

## Environment

- Python 3.11, macOS
- headroom version post Stage 3g merge

**Comment by inix-x** [comment]
Can't reproduce this on current `main` (HEAD `abab3ccb`) with a freshly built extension. It looks like a stale compiled `_core.abi3.so`, not a source defect, and the proposed fix would regress a live feature.

## What's on main

The Rust `SmartCrusherConfig` still has `lossless_only`, and the PyO3 constructor still accepts it:

- `crates/headroom-core/src/transforms/smart_crusher/config.rs:89`: `pub lossless_only: bool`
- `crates/headroom-py/src/lib.rs:483,510,537`: `lossless_only = false` in the `#[new]` signature, wired into `RustSmartCrusherConfig`

So `smart_crusher.py` passing `lossless_only` matches the Rust side. `git log -S lossless_only` shows the field was added in #1129 (Jun 23) and never removed.

## Before / after (your exact repro)

Against a **stale** `_core.abi3.so` (compiled before #1129):

```
SmartCrusherConfig.__new__() got an unexpected keyword argument 'lossless_only'
saved: 0
```

After `uv sync --reinstall-package headroom` recompiles the Rust from current source, same repo-local `.so`:

```
saved: 646
```

The constructor flips from rejecting `lossless_only` to accepting it. `compress()`, the proxy, and the MCP path all share that constructor, so one fresh build covers them.

## Why the proposed fix would regress

`lossless_only` is load-bearing in current Rust, not vestigial:

- `crusher.rs:709-741`: the strict-lossless early return, guarded by a `debug_assert!` that documents the Python per-call override `crush(..., lossless_only=True)` depends on it.
- `config.rs:124-125`: `opaque_markers_enabled()` gates offload on `enable_ccr_marker && !lossless_only`.

`kwargs.pop("lossless_only", None)` (plus dropping it from `_rust_cfg_kwargs`) would force the field `false`, silently kill the per-call `lossless_only=True` override, and break the marker-free, byte-recoverable guarantee.

## Stage 3g

The rewrite that supposedly removed the field never landed on `main`. Stage 3g is tracked as re-scope-or-close in `REALIGNMENT/12-decisions-needed.md` Q4 (issue #315), so the "after merging Stage 3g" premise doesn't hold here.

## Suggested resolution

@sfc-gh-nashukla your local extension is stale. A rebuild clears it:

```
uv sync --reinstall-package headroom   # or: maturin develop
```

@chopratejas @JerrettDavis  recommend closing as not-reproducible-on-main / stale build. If a future Stage 3g does remove the Rust field, the shim change belongs inside that PR so both sides stay in lockstep.

**Comment by JerrettDavis** [comment]
Closing as not-reproducible-on-main/stale.
